<!DOCTYPE html>
<html>
<body>
<?php
    $x="PHP";
    echo "Hello $x";
    echo "<br>";
    $y="This Is ";
    $z="My First Program Using PHP";
    echo $y.$z."<br>";
    echo "<h1>Muhammad Ali</h1>";
    echo "<p>Muhammad Ali was an American professional boxer, activist, entertainer, poet and philanthropist. Nicknamed The Greatest, he is widely regarded as one of the most significant and celebrated sports figures of the 20th century, and is frequently ranked as the greatest heavyweight boxer of all time.</p>";
 
    
    ?>
    </body>
</html>
